"""Updated

Revision ID: f42b37a628be
Revises: 
Create Date: 2024-10-25 12:19:48.016307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42b37a628be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=250), nullable=True))
        # Provide a name for the unique constraint
        batch_op.create_unique_constraint('uq_email', ['email'])  # Change None to a valid constraint name

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Use the same name to drop the constraint
        batch_op.drop_constraint('uq_email', type_='unique')  # Specify the name of the constraint
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
